# Generated by Django 5.2 on 2026-03-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0037_alter_product_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_start', 'Начало сессии'), ('session_end', 'Конец сессии'), ('screen_view', 'Просмотр экрана'), ('cart_add', 'Добавление в корзину'), ('cart_remove', 'Удаление из корзины'), ('search', 'Поисковый запрос'), ('promo_click', 'Клик по акции/баннеру')], db_index=True, max_length=30)),
                ('screen', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='main.customuser')),
            ],
            options={
                'db_table': 'analytics_events',
                'indexes': [models.Index(fields=['user', 'event_type'], name='analytics_user_type_idx'), models.Index(fields=['created_at'], name='analytics_created_idx')],
            },
        ),
    ]
