# Generated by Django 5.2 on 2025-09-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='onecclientmap',
            index=models.Index(fields=['one_c_guid'], name='api_onec_cl_one_c_g_2896bc_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptdedup',
            index=models.Index(fields=['created_at'], name='api_receipt_created_22a7a3_idx'),
        ),
    ]
