# Generated by Django 5.2 on 2025-09-10 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_onecclientmap_api_onec_cl_one_c_g_2896bc_idx_and_more'),
        ('main', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='onecclientmap',
            name='api_onec_cl_one_c_g_2896bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='receiptdedup',
            name='api_receipt_created_22a7a3_idx',
        ),
        migrations.AlterField(
            model_name='onecclientmap',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='onecclientmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.customuser'),
        ),
        migrations.AlterField(
            model_name='receiptdedup',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
