# Generated by Django 5.2 on 2025-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_onecclientmap_api_onec_cl_one_c_g_2896bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecclientmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='onecclientmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
