# Generated by Django 5.2 on 2025-09-23 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_onecclientmap_updated_at_and_more"),
        ("main", "0007_alter_customuser_referrer_alter_transaction_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onecclientmap",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="onec_client_maps",
                to="main.customuser",
            ),
        ),
    ]
