# Generated by Django 5.2 on 2026-03-10 03:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0037_alter_product_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Код')),
                ('push_title', models.CharField(max_length=200, verbose_name='Заголовок push')),
                ('push_body', models.TextField(verbose_name='Текст push')),
                ('start_at', models.DateTimeField(verbose_name='Начало')),
                ('end_at', models.DateTimeField(verbose_name='Окончание')),
                ('one_time_use', models.BooleanField(default=False, verbose_name='Одноразовая')),
                ('priority', models.IntegerField(default=100, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'db_table': 'campaigns',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Код')),
                ('segment_type', models.CharField(choices=[('manual', 'Ручной'), ('rule_based', 'По правилам')], default='manual', max_length=20, verbose_name='Тип сегмента')),
                ('rules', models.JSONField(blank=True, default=dict, verbose_name='Правила')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Сегмент клиентов',
                'verbose_name_plural': 'Сегменты клиентов',
                'db_table': 'customer_segments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('fixed_bonus', 'Фиксированный бонус'), ('bonus_percent', 'Процент бонусов'), ('fixed_plus_percent', 'Фикс + процент'), ('product_discount', 'Скидка на товар')], max_length=30, verbose_name='Тип награды')),
                ('reward_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Значение награды')),
                ('reward_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Процент награды')),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мин. сумма покупки')),
                ('stacking_mode', models.CharField(choices=[('stack_with_base', 'Суммировать с базовым'), ('replace_base', 'Заменить базовый')], default='stack_with_base', max_length=20, verbose_name='Режим наложения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='campaigns.campaign', verbose_name='Кампания')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_rules', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Правило кампании',
                'verbose_name_plural': 'Правила кампаний',
                'db_table': 'campaign_rules',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.customersegment', verbose_name='Сегмент'),
        ),
        migrations.CreateModel(
            name='CustomerCampaignAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначена')),
                ('synced_to_onec', models.BooleanField(default=False, verbose_name='Синхронизировано в 1С')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('used', models.BooleanField(default=False, verbose_name='Использована')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push отправлен')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки push')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='campaigns.campaign', verbose_name='Кампания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='main.customuser', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Назначение кампании',
                'verbose_name_plural': 'Назначения кампаний',
                'db_table': 'customer_campaign_assignments',
                'constraints': [models.UniqueConstraint(fields=('customer', 'campaign'), name='unique_customer_campaign')],
            },
        ),
    ]
