# Generated by Django 5.2 on 2026-03-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('main', '0039_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignrule',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Включает все дочерние подкатегории. Дерево разворачивает 1С.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_rules', to='main.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='campaignrule',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='campaign_rules_m2m', to='main.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='customercampaignassignment',
            name='receipt_id',
            field=models.CharField(blank=True, help_text='Внешний идентификатор чека из 1С для аудита', max_length=100, null=True, verbose_name='ID чека (1С)'),
        ),
        migrations.AlterField(
            model_name='campaignrule',
            name='min_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мин. сумма покупки (после скидок)'),
        ),
        migrations.AlterField(
            model_name='campaignrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_rules', to='main.product', verbose_name='Товар (deprecated, используйте products)'),
        ),
        migrations.AlterField(
            model_name='campaignrule',
            name='stacking_mode',
            field=models.CharField(choices=[('stack_with_base', 'Суммировать с базовым'), ('replace_base', 'Заменить базовый (не поддерживается v1)')], default='stack_with_base', max_length=20, verbose_name='Режим наложения'),
        ),
        migrations.AddConstraint(
            model_name='campaignrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('campaign',), name='unique_active_rule_per_campaign'),
        ),
    ]
