# Generated by Django 5.2 on 2026-03-24 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignrule_category_campaignrule_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audience_type',
            field=models.CharField(choices=[('customer_segment', 'CustomerSegment'), ('rfm_segment', 'RFM-сегмент')], default='customer_segment', max_length=20, verbose_name='Источник аудитории'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rfm_segment',
            field=models.CharField(blank=True, choices=[('champions', 'Champions'), ('loyal', 'Loyal'), ('potential_loyalists', 'Potential Loyalists'), ('new_customers', 'New Customers'), ('at_risk', 'At Risk'), ('hibernating', 'Hibernating'), ('lost', 'Lost')], help_text='Обязательно при audience_type = RFM-сегмент', max_length=50, null=True, verbose_name='RFM-сегмент'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, help_text='Обязательно при audience_type = CustomerSegment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.customersegment', verbose_name='CustomerSegment'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience_type', 'customer_segment'), _negated=True), models.Q(('segment__isnull', False), models.Q(('rfm_segment__isnull', True), ('rfm_segment', ''), _connector='OR')), _connector='OR'), name='campaign_cs_requires_segment'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience_type', 'rfm_segment'), _negated=True), models.Q(('segment__isnull', True), models.Q(('rfm_segment__isnull', True), ('rfm_segment', ''), _connector='OR', _negated=True)), _connector='OR'), name='campaign_rfm_requires_rfm_segment'),
        ),
    ]
