# Generated by Django 5.2 on 2026-03-24 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_add_audience_type_rfm_segment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campaign',
            name='campaign_rfm_requires_rfm_segment',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='audience_type',
            field=models.CharField(choices=[('customer_segment', 'Сегмент клиентов'), ('rfm_segment', 'RFM-сегмент')], default='customer_segment', max_length=20, verbose_name='Источник аудитории'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='rfm_segment',
            field=models.CharField(blank=True, choices=[('champions', 'Champions'), ('loyal', 'Loyal'), ('potential_loyalists', 'Potential Loyalists'), ('new_customers', 'New Customers'), ('at_risk', 'At Risk'), ('hibernating', 'Hibernating'), ('lost', 'Lost')], help_text='Заполните при источнике аудитории «RFM-сегмент».', max_length=50, null=True, verbose_name='RFM-сегмент'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, help_text='Заполните при источнике аудитории «Сегмент клиентов».', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.customersegment', verbose_name='Сегмент клиентов'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(('audience_type__in', ['customer_segment', 'rfm_segment'])), name='campaign_valid_audience_type'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience_type', 'rfm_segment'), _negated=True), models.Q(('segment__isnull', True), ('rfm_segment__in', ['champions', 'loyal', 'potential_loyalists', 'new_customers', 'at_risk', 'hibernating', 'lost'])), _connector='OR'), name='campaign_rfm_requires_valid_rfm_segment'),
        ),
    ]
