# Generated by Django 5.2 on 2026-03-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_tighten_enum_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campaign',
            name='campaign_rfm_requires_valid_rfm_segment',
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('audience_type', 'rfm_segment'), _negated=True), models.Q(('segment__isnull', True), ('rfm_segment__isnull', False), ('rfm_segment__in', ['champions', 'loyal', 'potential_loyalists', 'new_customers', 'at_risk', 'hibernating', 'lost'])), _connector='OR'), name='campaign_rfm_requires_valid_rfm_segment'),
        ),
    ]
