# Generated by Django 5.2 on 2026-03-26 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_fix_rfm_null_constraint'),
        ('main', '0040_customuser_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_guid', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='GUID чека')),
                ('reward_type', models.CharField(max_length=30, verbose_name='Тип награды')),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма бонусов')),
                ('is_accrual', models.BooleanField(default=True, verbose_name='Начисление')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='Последняя ошибка')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попыток отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_logs', to='campaigns.customercampaignassignment')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_logs', to='campaigns.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_reward_logs', to='main.customuser')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_logs', to='campaigns.campaignrule')),
            ],
            options={
                'verbose_name': 'Лог начисления по кампании',
                'verbose_name_plural': 'Логи начислений по кампаниям',
                'db_table': 'campaign_reward_log',
            },
        ),
    ]
