# Generated by Django 5.2 on 2026-03-10 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0037_alter_product_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRFMProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_days', models.IntegerField(blank=True, null=True, verbose_name='Recency (дни)')),
                ('frequency_count', models.IntegerField(default=0, verbose_name='Frequency (покупки)')),
                ('monetary_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monetary (сумма)')),
                ('r_score', models.IntegerField(default=1, verbose_name='R-score')),
                ('f_score', models.IntegerField(default=1, verbose_name='F-score')),
                ('m_score', models.IntegerField(default=1, verbose_name='M-score')),
                ('rfm_code', models.CharField(default='111', max_length=3, verbose_name='RFM-код')),
                ('segment_label', models.CharField(default='lost', max_length=50, verbose_name='Сегмент')),
                ('calculated_at', models.DateTimeField(verbose_name='Дата расчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_profile', to='main.customuser', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'RFM-профиль клиента',
                'verbose_name_plural': 'RFM-профили клиентов',
                'db_table': 'customer_rfm_profiles',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
