# Generated by Django 5.2 on 2026-03-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_product_stock'),
        ('rfm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBonusTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('champions', 'Champions'), ('standard', 'Standard')], max_length=20, verbose_name='Бонусный статус')),
                ('segment_label_at_fixation', models.CharField(help_text='segment_label, вычисленный при фиксации (аудит)', max_length=50, verbose_name='Сегмент при фиксации')),
                ('effective_from', models.DateField(verbose_name='Начало действия')),
                ('effective_to', models.DateField(verbose_name='Конец действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_tiers', to='main.customuser', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Месячный бонусный статус',
                'verbose_name_plural': 'Месячные бонусные статусы',
                'db_table': 'customer_bonus_tiers',
                'indexes': [models.Index(fields=['effective_from', 'effective_to'], name='idx_bonus_tier_period')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'effective_from'), name='unique_customer_bonus_tier_period')],
            },
        ),
    ]
