# Generated by Django 5.2 on 2026-03-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_product_stock'),
        ('rfm', '0002_customerbonustier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRFMHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_code', models.CharField(max_length=50, verbose_name='Сегмент')),
                ('previous_segment_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Предыдущий сегмент')),
                ('r_score', models.IntegerField(verbose_name='R-score')),
                ('f_score', models.IntegerField(verbose_name='F-score')),
                ('m_score', models.IntegerField(verbose_name='M-score')),
                ('recency_days', models.IntegerField(blank=True, null=True, verbose_name='Recency (дни)')),
                ('frequency_orders', models.IntegerField(default=0, verbose_name='Frequency (заказы)')),
                ('monetary_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monetary (сумма)')),
                ('transition_type', models.CharField(choices=[('initial', 'Initial'), ('segment_changed', 'Segment Changed'), ('score_changed', 'Score Changed')], max_length=20, verbose_name='Тип перехода')),
                ('calculated_at', models.DateTimeField(verbose_name='Рассчитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfm_history', to='main.customuser')),
            ],
            options={
                'db_table': 'rfm_customer_rfm_history',
                'ordering': ['-calculated_at'],
                'indexes': [
                    models.Index(fields=['customer', 'calculated_at'], name='rfm_hist_customer_calc_idx'),
                    models.Index(fields=['segment_code'], name='rfm_hist_segment_idx'),
                    models.Index(fields=['previous_segment_code'], name='rfm_hist_prev_segment_idx'),
                    models.Index(fields=['calculated_at'], name='rfm_hist_calc_at_idx'),
                ],
            },
        ),
    ]
