# Generated by Django 5.2 on 2026-03-22

from django.db import migrations
from django.utils import timezone


def backfill_rfm_history(apps, schema_editor):
    CustomerRFMProfile = apps.get_model("rfm", "CustomerRFMProfile")
    CustomerRFMHistory = apps.get_model("rfm", "CustomerRFMHistory")

    profiles = CustomerRFMProfile.objects.all()
    history_entries = []
    for profile in profiles:
        if not CustomerRFMHistory.objects.filter(
            customer_id=profile.customer_id,
            transition_type="initial",
        ).exists():
            history_entries.append(CustomerRFMHistory(
                customer_id=profile.customer_id,
                segment_code=profile.segment_label,
                previous_segment_code=None,
                r_score=profile.r_score,
                f_score=profile.f_score,
                m_score=profile.m_score,
                recency_days=profile.recency_days,
                frequency_orders=profile.frequency_count,
                monetary_total=profile.monetary_value,
                transition_type="initial",
                calculated_at=profile.updated_at or timezone.now(),
            ))
    if history_entries:
        CustomerRFMHistory.objects.bulk_create(history_entries)


def reverse_backfill(apps, schema_editor):
    CustomerRFMHistory = apps.get_model("rfm", "CustomerRFMHistory")
    CustomerRFMHistory.objects.filter(transition_type="initial").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rfm', '0003_add_customer_rfm_history'),
    ]

    operations = [
        migrations.RunPython(backfill_rfm_history, reverse_backfill),
    ]
