# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfm', '0004_backfill_rfm_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFMSegmentSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_customers', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('chunks_sent', models.IntegerField(default=0)),
                ('chunks_failed', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог синхронизации RFM в 1С',
                'verbose_name_plural': 'Логи синхронизации RFM в 1С',
                'db_table': 'rfm_segment_sync_log',
            },
        ),
    ]
