# Generated by Django 5.2 on 2025-09-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_product_one_c_guid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receipt_guid",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receipt_line",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="idempotency_key",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("receipt_guid", "receipt_line"), name="uniq_receipt_line"
            ),
        ),
    ]
