# Generated by Django 5.2 on 2025-12-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_customuser_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assembly', 'В сборке'), ('delivery', 'Курьер едет'), ('completed', 'Доставлен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
