# Generated by Django 5.2 on 2025-12-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_customuser_email_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_courier', 'Картой курьеру'), ('cash', 'Наличными'), ('sbp', 'СБП')], default='card_courier', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
