# Generated by Django 5.2 on 2025-12-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('inapp', 'In-app'), ('push', 'Push')], db_index=True, default='inapp', max_length=20, verbose_name='Источник')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Открыто')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_events', to='main.notification', verbose_name='Уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_open_events', to='main.customuser', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Открытие уведомления',
                'verbose_name_plural': 'Открытия уведомлений',
                'db_table': 'notification_open_events',
                'constraints': [models.UniqueConstraint(fields=('notification',), name='uniq_notification_open_once')],
            },
        ),
    ]
