# Generated by Django 5.2 on 2025-09-04 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptDedup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_guid', models.CharField(max_length=64, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('response_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_receipt_dedup',
            },
        ),
        migrations.CreateModel(
            name='OneCClientMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_c_guid', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onec_links', to='main.customuser')),
            ],
            options={
                'db_table': 'api_onec_client_map',
            },
        ),
    ]
