# Generated by Django 5.2 on 2026-03-14 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0039_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Score')),
                ('calculated_at', models.DateTimeField(verbose_name='Дата расчёта')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_rankings', to='main.customuser', verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Ранг товара',
                'verbose_name_plural': 'Ранги товаров',
                'db_table': 'product_rankings',
                'indexes': [models.Index(fields=['customer', '-score'], name='idx_ranking_customer_score')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'product'), name='uniq_customer_product_ranking'), models.UniqueConstraint(condition=models.Q(('customer__isnull', True)), fields=('product',), name='uniq_global_product_ranking')],
            },
        ),
    ]
