# Generated by Django 5.2 on 2026-02-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('assembly', 'Заказ собирается'), ('ready', 'Заказ собран, ждёт курьера'), ('delivery', 'Курьер забрал заказ и в пути'), ('arrived', 'Курьер пришёл и ждёт вас'), ('completed', 'Заказ доставлен'), ('canceled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
