# Generated by Django 5.2 on 2026-02-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_accepted_status_assembled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID курьера')),
                ('accepting_orders', models.BooleanField(default=True, verbose_name='Принимает заказы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Профиль курьера',
                'verbose_name_plural': 'Профили курьеров',
                'db_table': 'courier_profiles',
            },
        ),
        migrations.CreateModel(
            name='RoundRobinCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(unique=True, verbose_name='ID магазина')),
                ('last_courier_tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='Последний назначенный курьер')),
            ],
            options={
                'verbose_name': 'Round-Robin курсор',
                'verbose_name_plural': 'Round-Robin курсоры',
                'db_table': 'round_robin_cursors',
            },
        ),
    ]
