# Generated by Django 5.2 on 2026-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pickerprofile_courierprofile_staff_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='ID платежа ЮKassa'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('none', 'Нет онлайн-оплаты'), ('pending', 'Ожидает оплаты'), ('authorized', 'Авторизован (hold)'), ('captured', 'Списан'), ('canceled', 'Отменён'), ('failed', 'Ошибка')], default='none', max_length=20, verbose_name='Статус платежа'),
        ),
    ]
