# Generated by Django 5.2 on 2026-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_check_required',
            field=models.BooleanField(default=False, verbose_name='Требует ручной проверки'),
        ),
    ]
