# Generated by Django 5.2 on 2026-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_cancel_reason_canceled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_zone_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код зоны доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('client_refused', 'Клиент отказался'), ('client_absent', 'Клиент отсутствует'), ('long_wait', 'Клиент долго ждал'), ('damaged', 'Товар повреждён'), ('other', 'Другая причина')], max_length=20, null=True, verbose_name='Причина отмены'),
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зоны')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='Код номенклатуры 1С')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
                'db_table': 'delivery_zones',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('is_default',), name='delivery_zone_single_default')],
            },
        ),
    ]
