# Generated by Django 5.2 on 2026-03-24 04:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_product_stock'),
        ('orders', '0015_orderitemchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Списано бонусов'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('bonus_used__gte', 0)), name='order_bonus_used_non_negative'),
        ),
    ]
