# Generated by Django 5.2 on 2025-09-02 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('send_to_all', models.BooleanField(default=True, verbose_name='Всем пользователям')),
                ('target_user_ids', models.TextField(blank=True, help_text='Пример: 123456789, 987654321', null=True, verbose_name='ID пользователей (через запятую)')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'broadcast_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('store_id', models.IntegerField()),
                ('is_promotional', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.ForeignKey(blank=True, db_column='referrer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='main.customuser', to_field='telegram_id')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='BotActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_activities', to='main.customuser')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
                'db_table': 'bot_activities',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('purchase_time', models.TimeField(default=django.utils.timezone.now)),
                ('store_id', models.IntegerField()),
                ('is_promotional', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, db_index=True, null=True)),
                ('receipt_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('receipt_discount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('receipt_bonus_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('receipt_bonus_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
            },
        ),
    ]
