# Generated by Django 5.2 on 2025-12-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_order_last_sync_error_order_onec_guid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="FCM токен"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="android",
                        max_length=20,
                        verbose_name="Платформа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="main.customuser",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Устройство клиента",
                "verbose_name_plural": "Устройства клиентов",
                "db_table": "customer_devices",
            },
        ),
    ]
