# Generated by Django 5.2 on 2025-10-12 13:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_create_guest_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField()),
                ("telegram_message_id", models.BigIntegerField()),
                (
                    "open_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_deliveries",
                        to="main.customuser",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="main.broadcastmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доставка рассылки",
                "verbose_name_plural": "Доставки рассылок",
                "db_table": "newsletter_deliveries",
            },
        ),
        migrations.CreateModel(
            name="NewsletterOpenEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("raw_callback_data", models.CharField(blank=True, max_length=128)),
                ("telegram_user_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_events",
                        to="main.newsletterdelivery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Открытие рассылки",
                "verbose_name_plural": "Открытия рассылок",
                "db_table": "newsletter_open_events",
            },
        ),
        migrations.AddIndex(
            model_name="newsletterdelivery",
            index=models.Index(
                fields=["message", "customer"], name="newsletter_delivery_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletteropenevent",
            index=models.Index(
                fields=["delivery"], name="newsletter_open_delivery_idx"
            ),
        ),
    ]
