# Generated by Django 5.2 on 2025-12-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_sync_error',
            field=models.TextField(blank=True, null=True, verbose_name='Ошибка синхронизации'),
        ),
        migrations.AddField(
            model_name='order',
            name='onec_guid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='GUID 1С'),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_onec_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлен в 1С'),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_attempts',
            field=models.IntegerField(default=0, verbose_name='Попыток синхронизации'),
        ),
        migrations.AddField(
            model_name='order',
            name='sync_status',
            field=models.CharField(db_index=True, default='new', max_length=20, verbose_name='Синхр. статус'),
        ),
    ]
