# Generated by Django 5.2 on 2026-02-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_customuser_email_alter_product_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store_id',
            field=models.IntegerField(db_index=True, help_text='External store ID from 1C ERP (not a FK — Store model is managed by 1C)'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
    ]
