# Generated by Django 5.2 on 2026-03-25 07:31

from django.db import migrations, models


def backfill_card_id(apps, schema_editor):
    CustomUser = apps.get_model("main", "CustomUser")
    for user in CustomUser.objects.filter(card_id__isnull=True).iterator():
        user.card_id = f"LC-{user.pk:06d}"
        user.save(update_fields=["card_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='card_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Номер карты лояльности'),
        ),
        migrations.RunPython(backfill_card_id, migrations.RunPython.noop),
    ]
