# Generated by Django 5.2 on 2026-03-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_transaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз'), ('in_store', 'Покупка в магазине')], default='in_store', max_length=20, verbose_name='Тип покупки'),
        ),
    ]
